name: Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    name: Publish ${{ matrix.image }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: tdarr
            dockerfile: Dockerfile.tdarr
            tag: ghcr.io/empaa/tdarr:latest
          - image: tdarr_node
            dockerfile: Dockerfile.tdarr_node
            tag: ghcr.io/empaa/tdarr_node:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.image }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ matrix.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
